// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (project_id, user_id, content, message_type, room_name, attachment_url, attachment_type)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, user_id, content, message_type, room_name, created_at, attachment_url, attachment_type
`

type CreateChatMessageParams struct {
	ProjectID      int64         `json:"project_id"`
	UserID         sql.NullInt64 `json:"user_id"`
	Content        string        `json:"content"`
	MessageType    string        `json:"message_type"`
	RoomName       string        `json:"room_name"`
	AttachmentUrl  string        `json:"attachment_url"`
	AttachmentType string        `json:"attachment_type"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.ProjectID,
		arg.UserID,
		arg.Content,
		arg.MessageType,
		arg.RoomName,
		arg.AttachmentUrl,
		arg.AttachmentType,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Content,
		&i.MessageType,
		&i.RoomName,
		&i.CreatedAt,
		&i.AttachmentUrl,
		&i.AttachmentType,
	)
	return i, err
}

const getActiveCallForProject = `-- name: GetActiveCallForProject :one
SELECT room_name, message_type FROM chat_messages
WHERE project_id = ? AND message_type IN ('call_start', 'call_end')
ORDER BY id DESC
LIMIT 1
`

type GetActiveCallForProjectRow struct {
	RoomName    string `json:"room_name"`
	MessageType string `json:"message_type"`
}

func (q *Queries) GetActiveCallForProject(ctx context.Context, projectID int64) (GetActiveCallForProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCallForProject, projectID)
	var i GetActiveCallForProjectRow
	err := row.Scan(&i.RoomName, &i.MessageType)
	return i, err
}

const listChatAttachmentsByProject = `-- name: ListChatAttachmentsByProject :many
SELECT cm.id, cm.attachment_url, cm.attachment_type, cm.content, cm.created_at,
       COALESCE(u.name, 'Anonymous') AS user_name
FROM chat_messages cm
LEFT JOIN users u ON cm.user_id = u.id
WHERE cm.project_id = ? AND cm.attachment_url != ''
ORDER BY cm.created_at DESC
`

type ListChatAttachmentsByProjectRow struct {
	ID             int64     `json:"id"`
	AttachmentUrl  string    `json:"attachment_url"`
	AttachmentType string    `json:"attachment_type"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
	UserName       string    `json:"user_name"`
}

func (q *Queries) ListChatAttachmentsByProject(ctx context.Context, projectID int64) ([]ListChatAttachmentsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatAttachmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatAttachmentsByProjectRow
	for rows.Next() {
		var i ListChatAttachmentsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.AttachmentUrl,
			&i.AttachmentType,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesBefore = `-- name: ListChatMessagesBefore :many
SELECT cm.id, cm.project_id, cm.user_id, cm.content, cm.message_type, cm.room_name,
       cm.attachment_url, cm.attachment_type, cm.created_at,
       COALESCE(u.name, 'Anonymous') AS user_name
FROM chat_messages cm
LEFT JOIN users u ON cm.user_id = u.id
WHERE cm.project_id = ? AND cm.id < ?
ORDER BY cm.created_at DESC
LIMIT 50
`

type ListChatMessagesBeforeParams struct {
	ProjectID int64 `json:"project_id"`
	ID        int64 `json:"id"`
}

type ListChatMessagesBeforeRow struct {
	ID             int64         `json:"id"`
	ProjectID      int64         `json:"project_id"`
	UserID         sql.NullInt64 `json:"user_id"`
	Content        string        `json:"content"`
	MessageType    string        `json:"message_type"`
	RoomName       string        `json:"room_name"`
	AttachmentUrl  string        `json:"attachment_url"`
	AttachmentType string        `json:"attachment_type"`
	CreatedAt      time.Time     `json:"created_at"`
	UserName       string        `json:"user_name"`
}

func (q *Queries) ListChatMessagesBefore(ctx context.Context, arg ListChatMessagesBeforeParams) ([]ListChatMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesBefore, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesBeforeRow
	for rows.Next() {
		var i ListChatMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Content,
			&i.MessageType,
			&i.RoomName,
			&i.AttachmentUrl,
			&i.AttachmentType,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesByProject = `-- name: ListChatMessagesByProject :many
SELECT cm.id, cm.project_id, cm.user_id, cm.content, cm.message_type, cm.room_name,
       cm.attachment_url, cm.attachment_type, cm.created_at,
       COALESCE(u.name, 'Anonymous') AS user_name
FROM chat_messages cm
LEFT JOIN users u ON cm.user_id = u.id
WHERE cm.project_id = ?
ORDER BY cm.created_at DESC
LIMIT 100
`

type ListChatMessagesByProjectRow struct {
	ID             int64         `json:"id"`
	ProjectID      int64         `json:"project_id"`
	UserID         sql.NullInt64 `json:"user_id"`
	Content        string        `json:"content"`
	MessageType    string        `json:"message_type"`
	RoomName       string        `json:"room_name"`
	AttachmentUrl  string        `json:"attachment_url"`
	AttachmentType string        `json:"attachment_type"`
	CreatedAt      time.Time     `json:"created_at"`
	UserName       string        `json:"user_name"`
}

func (q *Queries) ListChatMessagesByProject(ctx context.Context, projectID int64) ([]ListChatMessagesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesByProjectRow
	for rows.Next() {
		var i ListChatMessagesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Content,
			&i.MessageType,
			&i.RoomName,
			&i.AttachmentUrl,
			&i.AttachmentType,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
