// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (project_id, user_id, content)
VALUES (?, ?, ?)
RETURNING id, project_id, user_id, content, created_at
`

type CreateChatMessageParams struct {
	ProjectID int64         `json:"project_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	Content   string        `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.ProjectID, arg.UserID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessagesBefore = `-- name: ListChatMessagesBefore :many
SELECT cm.id, cm.project_id, cm.user_id, cm.content, cm.created_at,
       COALESCE(u.name, 'Anonymous') AS user_name
FROM chat_messages cm
LEFT JOIN users u ON cm.user_id = u.id
WHERE cm.project_id = ? AND cm.id < ?
ORDER BY cm.created_at DESC
LIMIT 50
`

type ListChatMessagesBeforeParams struct {
	ProjectID int64 `json:"project_id"`
	ID        int64 `json:"id"`
}

type ListChatMessagesBeforeRow struct {
	ID        int64         `json:"id"`
	ProjectID int64         `json:"project_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UserName  string        `json:"user_name"`
}

func (q *Queries) ListChatMessagesBefore(ctx context.Context, arg ListChatMessagesBeforeParams) ([]ListChatMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesBefore, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesBeforeRow
	for rows.Next() {
		var i ListChatMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesByProject = `-- name: ListChatMessagesByProject :many
SELECT cm.id, cm.project_id, cm.user_id, cm.content, cm.created_at,
       COALESCE(u.name, 'Anonymous') AS user_name
FROM chat_messages cm
LEFT JOIN users u ON cm.user_id = u.id
WHERE cm.project_id = ?
ORDER BY cm.created_at DESC
LIMIT 100
`

type ListChatMessagesByProjectRow struct {
	ID        int64         `json:"id"`
	ProjectID int64         `json:"project_id"`
	UserID    sql.NullInt64 `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UserName  string        `json:"user_name"`
}

func (q *Queries) ListChatMessagesByProject(ctx context.Context, projectID int64) ([]ListChatMessagesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessagesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesByProjectRow
	for rows.Next() {
		var i ListChatMessagesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
