// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_items.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createKanbanItem = `-- name: CreateKanbanItem :one
INSERT INTO kanban_items (project_id, title, assignee_id, status)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, title, assignee_id, status, created_at, updated_at, created_by, updated_by
`

type CreateKanbanItemParams struct {
	ProjectID  int64         `json:"project_id"`
	Title      string        `json:"title"`
	AssigneeID sql.NullInt64 `json:"assignee_id"`
	Status     string        `json:"status"`
}

func (q *Queries) CreateKanbanItem(ctx context.Context, arg CreateKanbanItemParams) (KanbanItem, error) {
	row := q.db.QueryRowContext(ctx, createKanbanItem,
		arg.ProjectID,
		arg.Title,
		arg.AssigneeID,
		arg.Status,
	)
	var i KanbanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.AssigneeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteKanbanItem = `-- name: DeleteKanbanItem :exec
DELETE FROM kanban_items WHERE id = ?
`

func (q *Queries) DeleteKanbanItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKanbanItem, id)
	return err
}

const getKanbanItem = `-- name: GetKanbanItem :one
SELECT id, project_id, title, assignee_id, status, created_at, updated_at, created_by, updated_by FROM kanban_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetKanbanItem(ctx context.Context, id int64) (KanbanItem, error) {
	row := q.db.QueryRowContext(ctx, getKanbanItem, id)
	var i KanbanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.AssigneeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listKanbanItemsByProject = `-- name: ListKanbanItemsByProject :many
SELECT
    ki.id,
    ki.project_id,
    ki.title,
    ki.assignee_id,
    ki.status,
    ki.created_at,
    ki.updated_at,
    ki.created_by,
    ki.updated_by,
    u.name AS assignee_name
FROM kanban_items ki
LEFT JOIN users u ON u.id = ki.assignee_id
WHERE ki.project_id = ?
ORDER BY ki.status, ki.created_at
`

type ListKanbanItemsByProjectRow struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	Title        string         `json:"title"`
	AssigneeID   sql.NullInt64  `json:"assignee_id"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedBy    sql.NullInt64  `json:"created_by"`
	UpdatedBy    sql.NullInt64  `json:"updated_by"`
	AssigneeName sql.NullString `json:"assignee_name"`
}

func (q *Queries) ListKanbanItemsByProject(ctx context.Context, projectID int64) ([]ListKanbanItemsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanItemsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKanbanItemsByProjectRow
	for rows.Next() {
		var i ListKanbanItemsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.AssigneeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKanbanItem = `-- name: UpdateKanbanItem :one
UPDATE kanban_items
SET title       = ?,
    assignee_id = ?,
    status      = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, project_id, title, assignee_id, status, created_at, updated_at, created_by, updated_by
`

type UpdateKanbanItemParams struct {
	Title      string        `json:"title"`
	AssigneeID sql.NullInt64 `json:"assignee_id"`
	Status     string        `json:"status"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateKanbanItem(ctx context.Context, arg UpdateKanbanItemParams) (KanbanItem, error) {
	row := q.db.QueryRowContext(ctx, updateKanbanItem,
		arg.Title,
		arg.AssigneeID,
		arg.Status,
		arg.ID,
	)
	var i KanbanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.AssigneeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateKanbanItemStatus = `-- name: UpdateKanbanItemStatus :one
UPDATE kanban_items
SET status     = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, project_id, title, assignee_id, status, created_at, updated_at, created_by, updated_by
`

type UpdateKanbanItemStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateKanbanItemStatus(ctx context.Context, arg UpdateKanbanItemStatusParams) (KanbanItem, error) {
	row := q.db.QueryRowContext(ctx, updateKanbanItemStatus, arg.Status, arg.ID)
	var i KanbanItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.AssigneeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
