// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ChatMessage struct {
	ID          int64         `json:"id"`
	ProjectID   int64         `json:"project_id"`
	UserID      sql.NullInt64 `json:"user_id"`
	Content     string        `json:"content"`
	MessageType string        `json:"message_type"`
	RoomName    string        `json:"room_name"`
	CreatedAt   time.Time     `json:"created_at"`
}

type KanbanItem struct {
	ID         int64         `json:"id"`
	ProjectID  int64         `json:"project_id"`
	Title      string        `json:"title"`
	AssigneeID sql.NullInt64 `json:"assignee_id"`
	Status     string        `json:"status"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	CreatedBy  sql.NullInt64 `json:"created_by"`
	UpdatedBy  sql.NullInt64 `json:"updated_by"`
	DeletedAt  sql.NullTime  `json:"deleted_at"`
}

type Project struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      string        `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	CreatedBy   sql.NullInt64 `json:"created_by"`
	UpdatedBy   sql.NullInt64 `json:"updated_by"`
	GithubRepo  string        `json:"github_repo"`
}

type PushSubscription struct {
	ID        int64         `json:"id"`
	Endpoint  string        `json:"endpoint"`
	P256dh    string        `json:"p256dh"`
	Auth      string        `json:"auth"`
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	ApiToken     sql.NullString `json:"api_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedBy    sql.NullInt64  `json:"created_by"`
	UpdatedBy    sql.NullInt64  `json:"updated_by"`
}
