// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, endpoint)
	return err
}

const listPushSubscriptionsExcludingUser = `-- name: ListPushSubscriptionsExcludingUser :many
SELECT endpoint, p256dh, auth FROM push_subscriptions
WHERE user_id IS NULL OR user_id != ?
`

type ListPushSubscriptionsExcludingUserRow struct {
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

func (q *Queries) ListPushSubscriptionsExcludingUser(ctx context.Context, userID sql.NullInt64) ([]ListPushSubscriptionsExcludingUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsExcludingUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushSubscriptionsExcludingUserRow
	for rows.Next() {
		var i ListPushSubscriptionsExcludingUserRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (endpoint, p256dh, auth, user_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth = excluded.auth, user_id = excluded.user_id
`

type UpsertPushSubscriptionParams struct {
	Endpoint string        `json:"endpoint"`
	P256dh   string        `json:"p256dh"`
	Auth     string        `json:"auth"`
	UserID   sql.NullInt64 `json:"user_id"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushSubscription,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserID,
	)
	return err
}
